name: flutter_sdui_frontend
description: A Figma-like Flutter UI designer with drag and drop functionality.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  provider: ^6.1.1
  flutter_colorpicker: ^1.0.3
  flutter_sdui: 
    path: ../flutter-sdui-package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 